#!/usr/bin/env node
/* Builds an immutable exam content release from validated forms.
   Output layout (mirrors the private R2 bucket klarweg-exam-content):
     releases/<rel>/manifest.json
     releases/<rel>/level-configs/<lc>.json
     releases/<rel>/forms/<form>/module-<m>.json   KEYLESS browser packages (just-in-time per module)
     releases/<rel>/keys/<form>.json              SERVER ONLY (also imported into D1 item_keys)
     releases/<rel>/assets/<asset>.<ext>          media (synthetic: generated TEST AUDIO tones)
     registry.sql                                 D1 import for the exam database
   Packages are built from an explicit field whitelist and then scanned; any
   server-only field name in a package aborts the build.

   Usage: node exam-content/tools/build-release.mjs --release r000 [--out DIR] [formDir ...]
   (default --out: <os tmp>/klarweg-exam-build; nothing is uploaded — see docs/exam/RUNBOOK-EXAM-INFRA.md) */
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { ID, SERVER_ONLY_FIELDS } from '../schemas/content-model.mjs';
import { loadForm, loadLevelConfig, hoerenPlan, speakingPlan, toneWav, sha256 } from './lib.mjs';
import { validateForm, findForms } from './validate.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const REPO_ROOT = path.resolve(ROOT, '..');
export const slug = (id) => id.replace(/[^a-z0-9]+/gi, '_').replace(/^_|_$/g, '');
const OBJECTIVE = new Set(['binary_choice', 'mcq_single', 'matching_pool', 'speaker_assignment']);

export function buildRelease({ release, formDirs, levelsDir = path.join(ROOT, 'levels'), builtAt = new Date().toISOString(), repoRoot = REPO_ROOT }) {
  if (!ID.release.test(release || '')) throw new Error(`invalid release id ${release}`);
  const files = new Map();             // r2 key → Buffer
  const put = (key, data) => files.set(key, Buffer.isBuffer(data) ? data : Buffer.from(typeof data === 'string' ? data : JSON.stringify(data, null, 2)));
  const base = `releases/${release}`;
  const manifest = { release, built_at: builtAt, level_configs: [], forms: [], assets: {} };
  const sql = ['-- generated by exam-content/tools/build-release.mjs — import into D1 klarweg-exam', 'BEGIN TRANSACTION;'];
  const q = (v) => v === null || v === undefined ? 'NULL' : typeof v === 'number' ? String(v) : `'${String(v).replace(/'/g, "''")}'`;
  const seenLevelConfigs = new Set();

  for (const dir of formDirs) {
    /* The product repo is PUBLIC: only synthetic forms may live in it. Real
       forms (mock / set / anchor) and their keys come from a private content
       repository and are never committed here. */
    // realpath: a symlink inside the repo must not disguise where the content lives
    const kind = loadForm(dir).form?.kind;
    const real = fs.realpathSync(dir), realRepo = fs.realpathSync(repoRoot);
    const inRepo = path.resolve(dir).startsWith(path.resolve(repoRoot) + path.sep) || real.startsWith(realRepo + path.sep);
    if (kind && kind !== 'synthetic' && inRepo) {
      throw new Error(`refusing to build ${kind} form from inside the public product repo (${path.relative(repoRoot, dir)}); real exam content belongs in the private content repo`);
    }
    const v = validateForm(dir, { levelsDir });
    if (!v.ok) throw new Error(`form ${dir} failed validation:\n` + v.errors.map((e) => `  ${e.code}: ${e.msg}`).join('\n'));
    const { form, tasks, items, keys, assets } = loadForm(dir);
    const lc = loadLevelConfig(levelsDir, form.level_config);
    if (!seenLevelConfigs.has(lc.id)) {
      seenLevelConfigs.add(lc.id);
      put(`${base}/level-configs/${slug(lc.id)}.json`, lc);
      manifest.level_configs.push(lc.id);
      sql.push(`INSERT OR REPLACE INTO level_configs (id, level, version, json, created_at) VALUES (${q(lc.id)}, ${q(lc.level)}, ${q(Number(lc.id.split('@')[1]))}, ${q(JSON.stringify(lc))}, ${q(builtAt)});`);
    }
    const tasksById = Object.fromEntries(tasks.map((t) => [t.id, t]));
    const itemsById = Object.fromEntries(items.map((i) => [i.id, i]));
    const assetsById = Object.fromEntries(assets.map((a) => [a.id, a]));
    const fslug = slug(form.id);

    /* media */
    const durations = {};
    const assetModule = {};
    for (const t of tasks) for (const s of t.stimuli) assetModule[s.asset_id] = t.module;
    for (const it of items) for (const turn of it.response_spec?.turns || []) if (turn.prompt_asset) assetModule[turn.prompt_asset] = it.module;
    for (const fm of form.modules) for (const fp of fm.parts || []) if (fp.instruction_asset_id) assetModule[fp.instruction_asset_id] = fm.module;   // spoken Hören instructions
    const formAssets = [];
    for (const a of assets.filter((x) => x.kind === 'audio')) {
      let bytes, mime, duration;
      if (a.audio.generator) ({ bytes, mime, duration_ms: duration } = toneWav(a.audio.generator));
      else throw new Error(`asset ${a.id}: only generated synthetic audio is supported in Phase 5A`);
      durations[a.id] = duration;
      const key = `${base}/assets/${slug(a.id)}.wav`;
      put(key, bytes);
      const meta = { key, mime, bytes: bytes.length, sha256: sha256(bytes), duration_ms: duration, label: a.label || null, test_audio: true };
      manifest.assets[a.id] = meta;
      formAssets.push({ asset_id: a.id, module: assetModule[a.id] || null, ...meta });
    }

    /* keyless packages */
    const lcMod = (m) => lc.modules.find((x) => x.module === m);
    const modulesOut = {};
    for (const fm of form.modules) {
      const mc = lcMod(fm.module);
      const pkg = {
        package_version: 1, level: lc.level, variant: lc.variant, module: fm.module, navigation: mc.navigation,
        test_content: form.kind === 'synthetic',
        timing: mc.timing.kind === 'fixed' ? { kind: 'fixed', seconds: mc.timing.seconds }
          : mc.timing.kind === 'phase_plan' ? { kind: 'phase_plan', plan: hoerenPlan(lc, form, tasksById, itemsById, durations) }
            : { kind: 'speaking_phases', plan: speakingPlan(lc, form) },
        parts: fm.parts.map((fp) => {
          const pc = mc.parts.find((p) => p.part === fp.part);
          return {
            part: fp.part, construct: pc.construct, interaction: pc.interaction, advisory_seconds: pc.advisory_seconds ?? null,
            tasks: fp.task_ids.map((tid) => {
              const t = tasksById[tid];
              return {
                task_id: t.id, instructions: t.instructions.text_de, context_line: t.context_line || null,
                stimuli: t.stimuli.map((s) => {
                  const a = assetsById[s.asset_id];
                  return { role: s.role, asset_id: s.asset_id, kind: a.kind, label: s.label || a.label || null, order: s.order,
                    speaker_ids: s.speaker_ids || null, text: a.kind === 'text' ? a.text.body_md : null,
                    duration_ms: a.kind === 'audio' ? durations[a.id] : null };
                }),
                items: fp.item_order.filter((o) => t.items.includes(o.item_id)).map((o) => {
                  const it = itemsById[o.item_id];
                  const out = { item_id: it.id, display_no: o.display_no, interaction: it.interaction, stem: it.stem || null,
                    options: it.options ? it.options.map((op) => ({ option_id: op.option_id, label: op.label, text: op.text || null })) : null,
                    response_spec: publicResponseSpec(it.response_spec, durations), is_example: !!it.is_example };
                  if (it.is_example) out.example_answer = it.example_answer;
                  return out;
                })
              };
            })
          };
        }),
        rubric_structure: mc.scoring.strategy === 'rubric_double_rating'
          ? Object.fromEntries(Object.entries(lc.rubrics).filter(([, r]) => r.module === fm.module).map(([id, r]) => [id, { part: r.part, criteria: Object.keys(r.criteria) }]))   // criterion names only — point values stay server-side
          : null
      };
      assertNoLeak(pkg, `${form.id}/${fm.module}`);
      const key = `${base}/forms/${fslug}/module-${fm.module}.json`;
      put(key, pkg);
      modulesOut[fm.module] = { key, sha256: sha256(files.get(key)), bytes: files.get(key).length };
    }

    const keysKey = `${base}/keys/${fslug}.json`;
    put(keysKey, keys);
    manifest.forms.push({ id: form.id, kind: form.kind, label: form.label, level_config: form.level_config, rev: form.rev, status: form.status,
      modules: modulesOut, keys_key: keysKey, assets: formAssets.length });

    /* registry SQL */
    sql.push(`INSERT OR REPLACE INTO forms (id, level_config_id, kind, label, status, rev, release, created_at) VALUES (${q(form.id)}, ${q(form.level_config)}, ${q(form.kind)}, ${q(form.label)}, ${q(form.status)}, ${q(form.rev)}, ${q(release)}, ${q(builtAt)});`);
    for (const [m, o] of Object.entries(modulesOut)) {
      const order = lcMod(m).order;
      sql.push(`INSERT OR REPLACE INTO form_modules (form_id, module, module_order, package_key, package_sha256) VALUES (${q(form.id)}, ${q(m)}, ${order}, ${q(o.key)}, ${q(o.sha256)});`);
    }
    for (const fm of form.modules) for (const fp of fm.parts) for (const o of fp.item_order) {
      const it = itemsById[o.item_id];
      const scored = !it.is_example && OBJECTIVE.has(it.interaction) ? 1 : 0;
      const k = keys.keys[it.id];
      sql.push(`INSERT OR REPLACE INTO items_index (item_id, form_id, module, part, display_no, interaction, is_example, points, rubric_id) VALUES (${q(it.id)}, ${q(form.id)}, ${q(fm.module)}, ${fp.part}, ${q(o.display_no)}, ${q(it.interaction)}, ${it.is_example ? 1 : 0}, ${scored}, ${q(k.kind === 'rubric' ? k.rubric_id : null)});`);
      sql.push(`INSERT OR REPLACE INTO item_keys (item_id, form_id, key_json) VALUES (${q(it.id)}, ${q(form.id)}, ${q(JSON.stringify(k))});`);
    }
    for (const a of formAssets) sql.push(`INSERT OR REPLACE INTO form_assets (form_id, asset_id, module, r2_key, mime, bytes, sha256, duration_ms) VALUES (${q(form.id)}, ${q(a.asset_id)}, ${q(a.module)}, ${q(a.key)}, ${q(a.mime)}, ${a.bytes}, ${q(a.sha256)}, ${a.duration_ms});`);
  }
  sql.push('COMMIT;');
  put(`${base}/manifest.json`, manifest);
  return { release, manifest, files, sql: sql.join('\n') + '\n' };
}

function publicResponseSpec(rs, durations) {
  if (!rs) return null;
  if (rs.type === 'text') return { type: 'text', target_words: rs.target_words, editor: 'plain' };
  if (rs.type === 'audio') return { type: 'audio', max_seconds: rs.max_seconds, turns: (rs.turns || []).map((t) => ({ turn: t.turn, seconds: t.seconds, prompt_asset: t.prompt_asset || null, prompt_ms: t.prompt_asset ? durations[t.prompt_asset] : null })) };
  return { type: rs.type };
}

/* Leak scanner: no server-only field name may appear anywhere in a package. */
export function assertNoLeak(obj, where) {
  const bad = [];
  const walk = (o, p) => {
    if (Array.isArray(o)) return o.forEach((v, i) => walk(v, `${p}[${i}]`));
    if (o && typeof o === 'object') for (const [k, v] of Object.entries(o)) {
      if (SERVER_ONLY_FIELDS.includes(k) || k === 'correct' || k === 'key_json') bad.push(`${p}.${k}`);
      walk(v, `${p}.${k}`);
    }
  };
  walk(obj, '');
  if (bad.length) throw new Error(`package ${where} leaks server-only fields: ${bad.slice(0, 5).join(', ')}`);
}

export function writeRelease(build, outDir) {
  for (const [key, buf] of build.files) {
    const p = path.join(outDir, key);
    fs.mkdirSync(path.dirname(p), { recursive: true });
    fs.writeFileSync(p, buf);
  }
  fs.writeFileSync(path.join(outDir, 'registry.sql'), build.sql);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const argv = process.argv.slice(2);
  const opt = (n, d) => { const i = argv.indexOf(n); return i >= 0 ? argv[i + 1] : d; };
  const release = opt('--release', 'r000');
  const out = opt('--out', path.join(os.tmpdir(), 'klarweg-exam-build'));
  const dirs = argv.filter((a, i) => !a.startsWith('--') && !['--release', '--out'].includes(argv[i - 1]));
  const b = buildRelease({ release, formDirs: dirs.length ? dirs : findForms(path.join(ROOT, 'forms')) });
  writeRelease(b, out);
  console.log(JSON.stringify({ release, out, files: b.files.size, forms: b.manifest.forms.map((f) => f.id) }));
}
